# Auto-generated from the Dejaf Tadlu website catalog.
# Re-run extract_products.py against tadlu-store.html any time the site catalog changes,
# or edit this list by hand -- either way keeps the bot and the site in sync.

PRODUCTS = [
    {"id": 1, "name": "Yirgacheffe Coffee Beans, 250g", "cat": "Coffee & Tea", "price": 380, "sale": None},
    {"id": 18, "name": "Coffee Ceremony Tray Set", "cat": "Coffee & Tea", "price": 980, "sale": None},
    {"id": 36, "name": "Roasted Coffee Beans (የተቆላ ቡና), 250g", "cat": "Coffee & Tea", "price": 400, "sale": None},
    {"id": 37, "name": "Ground Coffee (የተፈጨ ቡና), 250g", "cat": "Coffee & Tea", "price": 420, "sale": None},
    {"id": 2, "name": "Traditional Clay Jebena", "cat": "Home & Kitchen", "price": 650, "sale": 550},
    {"id": 10, "name": "Electric Injera Mitad", "cat": "Home & Kitchen", "price": 3200, "sale": None},
    {"id": 3, "name": "Habesha Kemis, Hand-Embroidered", "cat": "Apparel", "price": 2200, "sale": None},
    {"id": 6, "name": "Handwoven Shemma Scarf", "cat": "Apparel", "price": 480, "sale": None},
    {"id": 11, "name": "Handmade Leather Sandals", "cat": "Apparel", "price": 620, "sale": None},
    {"id": 15, "name": "Habesha Netela, Cotton Shawl", "cat": "Apparel", "price": 900, "sale": None},
    {"id": 4, "name": "Berbere Spice Blend (በርበሬ), 200g", "cat": "Spices & Pantry", "price": 150, "sale": None},
    {"id": 5, "name": "Mitmita Spice Blend, 150g", "cat": "Spices & Pantry", "price": 140, "sale": None},
    {"id": 7, "name": "Ethiopian Cross Necklace, Silver", "cat": "Jewelry", "price": 950, "sale": 800},
    {"id": 9, "name": "Wireless Earbuds", "cat": "Electronics", "price": 2600, "sale": 2100},
    {"id": 16, "name": "USB-C Fast Charger, 20W", "cat": "Electronics", "price": 750, "sale": None},
    {"id": 13, "name": "Amharic Children's Storybook Set", "cat": "Books & Paper", "price": 260, "sale": None},
    {"id": 14, "name": "Frankincense & Myrrh Set", "cat": "Home & Garden", "price": 180, "sale": None},
    {"id": 17, "name": "Woven Mesob Basket", "cat": "Home & Garden", "price": 1400, "sale": 1150},
    {"id": 19, "name": "Teff Flour, 5kg", "cat": "Grocery", "price": 620, "sale": None},
    {"id": 20, "name": "Fresh Avocados, 1kg Bag", "cat": "Grocery", "price": 110, "sale": None},
    {"id": 21, "name": "Shiro Powder (ሽሮ), 500g", "cat": "Grocery", "price": 170, "sale": None},
    {"id": 22, "name": "Ethiopian Kibe Butter, 250g", "cat": "Grocery", "price": 210, "sale": 190},
    {"id": 29, "name": "Potatoes (ድንች), 1kg", "cat": "Grocery", "price": 45, "sale": None},
    {"id": 30, "name": "Carrots (ካሮት), 1kg", "cat": "Grocery", "price": 55, "sale": None},
    {"id": 31, "name": "Cabbage (ጎመን), 1 head", "cat": "Grocery", "price": 40, "sale": None},
    {"id": 32, "name": "Onions (ሽንኩርት), 1kg", "cat": "Grocery", "price": 65, "sale": None},
    {"id": 33, "name": "Garlic (ነጭ ሽንኩርት), 250g", "cat": "Grocery", "price": 90, "sale": None},
    {"id": 34, "name": "Tomatoes (ቲማቲም), 1kg", "cat": "Grocery", "price": 70, "sale": 60},
    {"id": 35, "name": "Cooking Oil (ዘይት), 1L", "cat": "Grocery", "price": 260, "sale": None},
    {"id": 23, "name": "Shea Butter Body Cream", "cat": "Beauty & Cosmetics", "price": 240, "sale": None},
    {"id": 24, "name": "Natural Henna Powder, 100g", "cat": "Beauty & Cosmetics", "price": 130, "sale": None},
    {"id": 25, "name": "Matte Lipstick Set", "cat": "Beauty & Cosmetics", "price": 390, "sale": 320},
    {"id": 26, "name": "Voltage Stabilizer, 1000VA", "cat": "Electrical Equipment", "price": 1850, "sale": None},
    {"id": 27, "name": "LED Bulb Pack, 4 x 9W", "cat": "Electrical Equipment", "price": 340, "sale": None},
    {"id": 28, "name": "Rechargeable Emergency Lamp", "cat": "Electrical Equipment", "price": 590, "sale": 480},
    {"id": 38, "name": "Kids Pajama Set, Assorted Prints", "cat": "Apparel", "price": 480, "sale": None},
    {"id": 39, "name": "Kids Pajama Pants, Assorted Prints", "cat": "Apparel", "price": 260, "sale": None},
    {"id": 40, "name": "Girls Leggings, Navy & Lilac", "cat": "Apparel", "price": 320, "sale": None},
    {"id": 41, "name": "Eau de Parfum, For Women", "cat": "Beauty & Cosmetics", "price": 950, "sale": None},
    {"id": 42, "name": "Eau de Parfum, For Men, 50ml", "cat": "Beauty & Cosmetics", "price": 850, "sale": None},
    {"id": 43, "name": "Men's Pullover Hoodie", "cat": "Apparel", "price": 900, "sale": None},
    {"id": 44, "name": "Men's Pique Polo Shirt", "cat": "Apparel", "price": 650, "sale": None},
    {"id": 45, "name": "Men's Boxer Shorts, Assorted Patterns (6-Pack)", "cat": "Apparel", "price": 780, "sale": None},
]

CATEGORIES = sorted(set(p['cat'] for p in PRODUCTS))